//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Entidades.SentenciasSQL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _SQLSupport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _SQLSupport() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_Entidades.SentenciasSQL._SQLSupport", typeof(_SQLSupport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contratoIndex @startIndex,@perPage,@CampoBuscar,@valorBuscar,@TotalREG OUT.
        /// </summary>
        internal static string contratoIndex {
            get {
                return ResourceManager.GetString("contratoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contratoSave @UUID,@EmpresaRUC,@PlanID,@FechaINI,@FechaFIN,@MinutosPLAN,@Observaciones,@EstadoREG,@isNew.
        /// </summary>
        internal static string contratoSave {
            get {
                return ResourceManager.GetString("contratoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a empresaIndex @startIndex,@perPage,@CampoBuscar,@valorBuscar,@TotalREG OUT.
        /// </summary>
        internal static string empresaIndex {
            get {
                return ResourceManager.GetString("empresaIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.empresaSave @empresaRUC,@empresaNOM,@empresaDIR,@empresaTEL,@UUID,@estadoREG,@isNew.
        /// </summary>
        internal static string empresaSave {
            get {
                return ResourceManager.GetString("empresaSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a planCombos @a.
        /// </summary>
        internal static string planCMB {
            get {
                return ResourceManager.GetString("planCMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a planSave @Descripcion,@Minutos,@UUID,@estadoREG,@isNew.
        /// </summary>
        internal static string planGuardar {
            get {
                return ResourceManager.GetString("planGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ticket_siIndex @startIndex,@perPage,@ticketNumero,@ticketEmpresa,@ticketPrioridad,@ticketEstado,@TotalREG OUT.
        /// </summary>
        internal static string RecuperaTickets {
            get {
                return ResourceManager.GetString("RecuperaTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuarioIndex @startIndex,@perPage,@CampoBuscar,@valorBuscar,@TotalREG OUT.
        /// </summary>
        internal static string usuarioIndex {
            get {
                return ResourceManager.GetString("usuarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Login @email,@password.
        /// </summary>
        internal static string usuarioLogin {
            get {
                return ResourceManager.GetString("usuarioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuarioSave @UUID,@Nombre,@Email,@Password,@Horario,@EmpresaRUC,@Estado,@isNew.
        /// </summary>
        internal static string usuarioSave {
            get {
                return ResourceManager.GetString("usuarioSave", resourceCulture);
            }
        }
    }
}
